language: ruby
rvm:
- 2.3.3

install: gem install jekyll html-proofer jekyll-sitemap jekyll-feed jekyll-paginate

script: scripts/build.sh

env:
  global:
  - NOKOGIRI_USE_SYSTEM_LIBRARIES=true

sudo: false

deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  on:
    branch: master
