title: Gerrit Beine
tagline: Meditations on Agile
email: mail@gerritbeine.com

author:
  name:        "Gerrit Beine"
  email:       "mail@gerritbeine.com"
  xing:        "Gerrit_Beine"
  linkedin:    "gerritbeine"
  slideshare:  "gerritbeine"
  twitter:     "GerritBeine"
  google-plus: "gerritbeine"
  github:      "gbeine"
  goodreads:   "31186993-gerrit-beine"
  youtube:     "UCqu6H_0moQmU77YRpsaWudg"

collections:
  tags:
    output: true
    permalink: /tag/:name/

navigation:
- title: About
  url: /about
- title: Imprint
  url: /imprint
- title: Trainings
  url: /trainings

permalink: /:year/:month/:title/
timezone: Europe/Berlin

markdown: kramdown
excerpt_separator: "\n\n\n"
highlighter: rouge
encoding: utf-8
# paginate: 5
# paginate_path: '/page/:num/'

theme: minima

sass:
  style: compressed

plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-seo-tag

exclude:
  - .git
  - .gitignore
  - .sass-cache
  - Gemfile
  - Gemfile.lock
  - sass
  - scripts
  - vendor
